### ISSUE TITLE
Grid transparency set to 0 for brief second when TA is enabled

### ISSUE THREAD

**Issue by MrUnit64** [MrUnit64/TransformAnarchy#25]
A small but very annoying visual bug: The transparency of the ingame grid is set to 0 for 0.1 seconds when enabling TA making the screen / grid "flash". Very distracting. 

https://github.com/MrUnit64/TransformAnarchy/assets/109811217/4dccae64-9cdb-4780-bef0-2efbbae4f9ab

**Comment by Distantz** [comment]
Seems this is due to RA waiting a frame to enable the gizmo. I have a 160Hz display on my laptop so didn't catch this during development. Any ideas on fixes?

**Comment by Distantz** [comment]
Inspecting the frames of the video, it seems that the builder grid is enabled when the gizmo is enabled, then it's disabled a few frames later. Not sure of the cause of this.

**Comment by MrUnit64** [comment]
Solved in latest dev build
