### ISSUE TITLE
Rotating Blueprints on Z-Axis not yet working

### ISSUE THREAD

**Issue by MrUnit64** [MrUnit64/TransformAnarchy#30]
Rotating Blueprints on Z-Axis not yet working - snapping back to other angles

**Comment by Distantz** [comment]
This is an issue with the games codebase. The blueprint and flatride builder commands take a direction and use the default up vector to figure out orientation. Not sure how to fix without completely rewriting / replacing both. Would also possibly just break multiplayer. Will not be worked on.
