### ISSUE TITLE
Gizmo rendering behind active object

### ISSUE THREAD

**Issue by MrUnit64** [MrUnit64/TransformAnarchy#31]
The gizmo components currently render behind the active object the player is building. Very annoying when the object is larger than the gizmo, which can now happen with the new scale modifier.

**Comment by Distantz** [comment]
Requires a new shader, could be possible, loading shaders via the AssetBundle is completely valid and should work.

**Comment by MrUnit64** [comment]
I have no idea how loading shaders works outside of Unity, but this seems the biggest issue for TA in general right now so I hope it's fixable.

**Comment by MrUnit64** [comment]
Fixed in latest dev build
